FUNCTION ZRFC_PRD_REQUEST_EXPROT_GIT.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     VALUE(FILES) TYPE  ZTS_REQUEST_FILE_GIT
*"     VALUE(REQUESTNOS) TYPE  STRING
*"----------------------------------------------------------------------
  DATA: LW_FILES TYPE ZTS_REQUEST_FILE_LINE_GIT.
  DATA: LW_DATA TYPE SDOKCNTBIN.
  DATA: LINES TYPE I.
  DATA: INDX TYPE I .

  LOOP AT FILES INTO LW_FILES .
    INDX = 0.
    OPEN DATASET LW_FILES-FILENAME FOR OUTPUT IN BINARY MODE.

    DESCRIBE TABLE LW_FILES-DATA LINES LINES.
    LOOP AT LW_FILES-DATA INTO LW_DATA.
      INDX = INDX + 1.
      IF INDX <> LINES.
        TRANSFER LW_DATA-LINE TO LW_FILES-FILENAME.
      ELSE.
        TRANSFER LW_DATA-LINE+(LW_FILES-LAST_LINE_SIZE) TO LW_FILES-FILENAME.
      ENDIF.
    ENDLOOP.
    CLOSE DATASET LW_FILES-FILENAME.
  ENDLOOP.

  DATA: RESULT_TAB TYPE TABLE OF STRING WITH HEADER LINE.
  SPLIT REQUESTNOS AT ',' INTO TABLE  RESULT_TAB IN CHARACTER MODE.

  DATA: REQ TYPE TMSBUFFER-TRKORR.

  LOOP AT RESULT_TAB.
    REQ =  RESULT_TAB.
    CALL FUNCTION 'TMS_MGR_FORWARD_TR_REQUEST'
      EXPORTING
        IV_REQUEST = REQ
        IV_TARGET  = 'PRE'
        IV_TARDOM  = 'DOMAIN_PRE'.
    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
      WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.

    CALL FUNCTION 'TMS_MGR_IMPORT_TR_REQUEST'
      EXPORTING
        IV_SYSTEM  = 'PRE'
        IV_DOMAIN  = 'DOMAIN_PRE'
        IV_CLIENT = '800'
        IV_REQUEST = REQ.
    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
      WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.
  ENDLOOP.



ENDFUNCTION.
