*&---------------------------------------------------------------------*
*& Report ZGIT013
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT013.

TABLES: SSCRFIELDS,LIPS.                     "工具栏上添加按键
DATA FUNCTXT TYPE SMP_DYNTXT.          "工具栏上添加按键

"标准的两输入框
SELECTION-SCREEN BEGIN OF  BLOCK S1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: DATA FOR SY-DATUM,
      TIME FOR SY-UZEIT DEFAULT '123000'  NO INTERVALS,
      S_VBELN FOR LIPS-VBELN MATCHCODE OBJECT VMVL.
SELECTION-SCREEN END OF   BLOCK S1.

SELECTION-SCREEN: ULINE /1(82).
SELECTION-SCREEN: ULINE 83(83)."接着上面线继续画


SELECTION-SCREEN BEGIN OF BLOCK S2 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN COMMENT (8) text-t01.   "添加文本  “期间
SELECTION-SCREEN COMMENT (8) PTXT.   "添加文本  “期间
SELECTION-SCREEN COMMENT 10(8) TEXT-T02 FOR FIELD P_BEGDA . "开始日期 "从    “30(8）30向左上 8显示长度
PARAMETERS:P_BEGDA TYPE D DEFAULT SY-DATUM .

SELECTION-SCREEN COMMENT 40(8) TEXT-T03 FOR FIELD P_ENDDA. "结束日期 “30(8）30向左上 8显示长度
PARAMETERS:P_ENDDA TYPE D DEFAULT SY-DATUM.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK S2.

SELECTION-SCREEN BEGIN OF BLOCK S3 WITH FRAME TITLE TEXT-003.
PARAMETERS:R1 RADIOBUTTON GROUP RG DEFAULT 'X' USER-COMMAND RG,
           R2 RADIOBUTTON GROUP RG,
           R3 RADIOBUTTON GROUP RG.
*SELECTION-SCREEN BEGIN OF LINE.

*SELECTION-SCREEN COMMENT (2) text-t04.
PARAMETERS:C1 AS  CHECKBOX USER-COMMAND C1.
*SELECTION-SCREEN COMMENT 8(2) text-t05.
PARAMETERS:C2 AS CHECKBOX.

*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN:PUSHBUTTON (20) BUTTON USER-COMMAND BCOM.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK S3.


SELECTION-SCREEN BEGIN OF BLOCK S4 WITH FRAME TITLE TEXT-004.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(79) TEXT1.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(79) TEXT2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK S4.


SELECTION-SCREEN: ULINE /1(82).
SELECTION-SCREEN: ULINE 83(83).


SELECTION-SCREEN: BEGIN OF SCREEN 100  AS SUBSCREEN.
PARAMETERS:SP1 TYPE C.
SELECTION-SCREEN:END OF SCREEN 100.


SELECTION-SCREEN: BEGIN OF SCREEN 200  AS SUBSCREEN.
PARAMETERS:SP2 TYPE C.
SELECTION-SCREEN:END OF SCREEN 200.


SELECTION-SCREEN:BEGIN OF TABBED BLOCK  MYTAB FOR 10 LINES,
  TAB (10) TBUT1 USER-COMMAND PUSH1 DEFAULT SCREEN 100,
  TAB (10) TBUT2 USER-COMMAND PUSH2 DEFAULT SCREEN 200,
  END OF BLOCK MYTAB .


SELECTION-SCREEN: FUNCTION KEY 1,  "工具栏上添加按键
                  FUNCTION KEY 2,  "工具栏上添加按键
                  FUNCTION KEY 3.  "工具栏上添加按键

INITIALIZATION.
  TEXT1 = '1.程序相关文档描述'.
  TEXT2 = '2.程序相关描述'.
  TBUT1  = 'tbut1'.
  TBUT2  = 'tbut2'.

  CONCATENATE ICON_MANAGER '输入期间' INTO PTXT.   "给文本加入图片

  CALL FUNCTION 'ICON_CREATE' " 给按钮添加图标和文本
    EXPORTING
      NAME   = ICON_SEARCH   " 按钮的图片的名字
      TEXT   = '搜   索'                   "按钮的文本
      INFO   = 'SEARCH'
    IMPORTING
      RESULT = BUTTON
    EXCEPTIONS
      OTHERS = 0.

  "工具栏添加按键
  FUNCTXT-ICON_ID   = ICON_CREATE.     "工具栏上添加按键
  FUNCTXT-ICON_TEXT = '新增'.          "工具栏上添加按键
  SSCRFIELDS-FUNCTXT_01 = FUNCTXT.     "工具栏上添加按键

  FUNCTXT-ICON_ID   = ICON_CHANGE.     "工具栏上添加按键
  FUNCTXT-ICON_TEXT = '修改'.          "工具栏上添加按键
  SSCRFIELDS-FUNCTXT_02 = FUNCTXT.     "工具栏上添加按键

  FUNCTXT-ICON_ID   = ICON_DELETE.     "工具栏上添加按键
  FUNCTXT-ICON_TEXT = '删除'.          "工具栏上添加按键
  SSCRFIELDS-FUNCTXT_03 = FUNCTXT.     "工具栏上添加按键

AT SELECTION-SCREEN.

  LOOP AT  SCREEN.
    MODIFY SCREEN .
  ENDLOOP.

  MESSAGE SY-UCOMM TYPE 'S'.
  CASE  SY-UCOMM.
    WHEN 'BCOM'.
      MESSAGE '点击搜索search' TYPE 'S'.

    WHEN OTHERS.
  ENDCASE.
