*&---------------------------------------------------------------------*
*& Report ZGIT023
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT023.

DATA:IT_EDIDC TYPE STANDARD TABLE OF EDIDC WITH HEADER LINE,
     IT_EDIDD TYPE TABLE OF EDIDD WITH HEADER LINE,
     WA_EDIDC TYPE EDIDC,
     WA_BKPF  TYPE ZFIDOCH,
     WA_BSEG  TYPE ZFIDOCI.


SELECT * INTO TABLE @DATA(IT_BKPF) FROM BKPF WHERE BUKRS = '1100' AND BELNR = '0090000000' AND GJAHR = '2020'.
SELECT * INTO TABLE @DATA(IT_BSEG) FROM BSEG WHERE BUKRS = '1100' AND BELNR = '0090000000' AND GJAHR = '2020'.


LOOP AT IT_BKPF  ASSIGNING FIELD-SYMBOL(<WA_BKPF>).
  IT_EDIDD-SEGNAM = 'ZFIDOCH'."节点名称
*  IT_EDIDD-DTINT2 = 0.
  IT_EDIDD-HLEVEL = '1'."层次级别
  MOVE-CORRESPONDING <WA_BKPF> TO WA_BKPF.
  IT_EDIDD-SDATA = WA_BKPF.
  APPEND IT_EDIDD.
  CLEAR:WA_BKPF,IT_EDIDD.
ENDLOOP.

LOOP AT IT_BSEG  ASSIGNING FIELD-SYMBOL(<WA_BSEG>).
  IT_EDIDD-SEGNAM = 'ZFIDOCI'."节点名称
*  IT_EDIDD-DTINT2 = 0.
  IT_EDIDD-HLEVEL = '2'."层次级别
  MOVE-CORRESPONDING <WA_BSEG> TO WA_BSEG.
  IT_EDIDD-SDATA = WA_BSEG.
  APPEND IT_EDIDD.
  CLEAR:WA_BSEG,IT_EDIDD.
ENDLOOP.

WA_EDIDC-MESTYP = 'ZFIMT'."messge type
WA_EDIDC-IDOCTP = 'ZFIIDOCBY'."idoc type
"WA_EDIDC-RCVPRN = 'CLIENT400'.
WA_EDIDC-RCVPRN = 'SAPDVA400'."接受方合伙伙伴编号
WA_EDIDC-RCVPRT = 'LS'.
WA_EDIDC-OUTMOD = '2'."立即发送

CALL FUNCTION 'MASTER_IDOC_DISTRIBUTE'
  EXPORTING
    MASTER_IDOC_CONTROL            = WA_EDIDC
  TABLES
    COMMUNICATION_IDOC_CONTROL     = IT_EDIDC
    MASTER_IDOC_DATA               = IT_EDIDD
  EXCEPTIONS
    ERROR_IN_IDOC_CONTROL          = 1
    ERROR_WRITING_IDOC_STATUS      = 2
    WRROR_IN_IDOC_DATA             = 3
    SENDING_LOGICAL_SYSTEM_UNKNOWN = 4
    OTHERS                         = 5.

"解锁对应的IDOC号直接发送IDOC
READ TABLE IT_EDIDC ASSIGNING FIELD-SYMBOL(<WA_EDIDC>) INDEX 1.
IF SY-SUBRC = 0.
  CALL FUNCTION 'EDI_DOCUMENT_DEQUEUE_LATER'
    EXPORTING
      DOCNUM = <WA_EDIDC>-DOCNUM.
ENDIF.

IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
  WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ELSE.
  COMMIT WORK AND WAIT.
  WRITE:'IDOC SENT:'.
  LOOP AT IT_EDIDC INTO WA_EDIDC.
    NEW-LINE.
    WRITE:'IDOC number is',WA_EDIDC-DOCNUM,
    ';receiver partner is',WA_EDIDC-RCVPRN,
    '; sender partner',WA_EDIDC-SNDPRN.
  ENDLOOP.
ENDIF.




*DATA: LS_POHEAD TYPE ZPOHEAD, "IDoc数据段：头
*      LS_POITEM TYPE YPOITEM, "IDoc数据段：Item
*      LS_EDIDC  TYPE EDIDC, "IDoc的控制记录
*      LT_EDIDC  TYPE TABLE OF EDIDC,
*      LT_EDIDD  TYPE TABLE OF EDIDD WITH HEADER LINE. "IDoc的数据记录
*CLEAR LS_EDIDC.
**系统根据下面4行即可与WE20(合作和伴配置文件)设置关联起来
*LS_EDIDC-MESTYP = 'YPO_MESS_TYPE'. "Message Type
*LS_EDIDC-IDOCTP = 'YPOIDOC'. "IDOC Type
*LS_EDIDC-RCVPRN = 'SAPDEV600'. "partner Number of Recipient接收方合作伙伴
*LS_EDIDC-RCVPRT = 'LS'.      "partner Type of Receiver接收方类型为逻辑系统
*
**添加IDOC节点
*CLEAR LT_EDIDD.
*LT_EDIDD-SEGNAM = 'ZPOHEAD'."头节点
*LT_EDIDD-DTINT2 = 0.
*CLEAR LS_POHEAD.
*LS_POHEAD-EBELN = '4500001576'."采购单号
*LS_POHEAD-BUKRS = '1100'."公司代码
*LS_POHEAD-BEDAT = '20090630'."日期
*LT_EDIDD-SDATA = LS_POHEAD. "节点内容：ls_pohead结构中的数据最后被拼接成字符串再赋值给lt_edidd-sdata，最大长度不能超过1000
*APPEND LT_EDIDD.
*
*CLEAR LT_EDIDD.
*LT_EDIDD-SEGNAM = 'YPOITEM'."Item节点
*LT_EDIDD-DTINT2 = 0.
*CLEAR LS_POITEM.
*LS_POITEM-EBELN = '4500001576'."采购单号
*LS_POITEM-EBELP = '00010'."Item行号
*LS_POITEM-MATNR = '000000302010000011'."物料号
*LS_POITEM-MENGE = '2'."数量
*LS_POITEM-MEINS = 'ST'."单位
*LT_EDIDD-SDATA = LS_POITEM.
*APPEND LT_EDIDD.
*
*CLEAR LT_EDIDD.
*LT_EDIDD-SEGNAM = 'YPOITEM'."Item节点
*LT_EDIDD-DTINT2 = 0.
*CLEAR LS_POITEM.
*LS_POITEM-EBELN = '4500001576'."采购单号
*LS_POITEM-EBELP = '00020'."Item行号
*LS_POITEM-MATNR = '000000301010000049'."物料号
*LS_POITEM-MENGE = '2'."数量
*LS_POITEM-MEINS = 'ST'."单位
*LT_EDIDD-SDATA = LS_POITEM.
*APPEND LT_EDIDD.
*
*CALL FUNCTION 'MASTER_IDOC_DISTRIBUTE' "发送IDoc
*  EXPORTING
*    MASTER_IDOC_CONTROL            = LS_EDIDC "IDoc控制记录
*  TABLES
*    COMMUNICATION_IDOC_CONTROL     = LT_EDIDC "接收：用来接收IDoc发送情况
*    MASTER_IDOC_DATA               = LT_EDIDD "IDoc数据记录
*  EXCEPTIONS "
*    ERROR_IN_IDOC_CONTROL          = 1
*    ERROR_WRITING_IDOC_STATUS      = 2
*    ERROR_IN_IDOC_DATA             = 3
*    SENDING_LOGICAL_SYSTEM_UNKNOWN = 4
*    OTHERS                         = 5.
*IF SY-SUBRC <> 0.
*  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
*ELSE.
*  COMMIT WORK.
*  WRITE: 'Idoc sent:'.
*  LOOP AT LT_EDIDC INTO LS_EDIDC.
*    NEW-LINE.
*    WRITE: 'Idoc number is', LS_EDIDC-DOCNUM,
*           '; receiver partner is', LS_EDIDC-RCVPRN,
*           '; sender partner',LS_EDIDC-SNDPRN.
*  ENDLOOP.
*ENDIF.
*
** 0000000000213239
