*&---------------------------------------------------------------------*
*& Report ZGIT025
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT025.

*PARAMETERS: PROGNAME(120).       "程序名称
DATA:STR     TYPE STRING,
     REP_STR TYPE STRING.
DATA:BEGIN OF IT_REPORT OCCURS 0,
       ROW TYPE CHAR3000,
     END OF IT_REPORT.

DATA:BEGIN OF IT_TYPE OCCURS 0,
       ROW TYPE CHAR3000,
     END OF IT_TYPE.

DATA:BEGIN OF IT_SQL OCCURS 0,
       ROW TYPE CHAR3000,
     END OF IT_SQL.

DATA:BEGIN OF IT_LAYOUT OCCURS 0,
       ROW TYPE CHAR3000,
     END OF IT_LAYOUT.

DATA:BEGIN OF IT_STRUC  OCCURS 0,
       TABNAME     TYPE CHAR30,
       FIELDNAME   TYPE CHAR30,
       FIELDASNAME TYPE CHAR30,
       FIELDDESC   TYPE CHAR30,
     END OF IT_STRUC.

DATA:BEGIN OF IT_TAB OCCURS 0,
       TABNAME   TYPE CHAR30,
       TABASNAME TYPE CHAR30,
     END OF IT_TAB.

DATA:IT_ITEM TYPE STANDARD TABLE OF QALS WITH HEADER LINE.
"---------------------------------------------------------SQL编辑区

DATA:BEGIN OF IT_DATA OCCURS 0,
       POSNR TYPE VBAP-POSNR,
       VBELN TYPE VBAP-POSNR,
     END OF IT_DATA.

"---------------------------------------------------------SQL编辑区

READ REPORT 'ZGIT025' INTO IT_REPORT.

LOOP AT  IT_REPORT.
  STR = IT_REPORT-ROW.
  TRANSLATE STR TO UPPER CASE.

  FIND 'DATA:BEGIN OF IT_DATA OCCURS 0,' IN STR.
  IF SY-SUBRC = 0.
    DATA(L_BEGIN_SQL) = 'X'."sql 开始标识
  ENDIF.

  IF L_BEGIN_SQL = 'X'.
    IT_SQL-ROW = IT_REPORT-ROW.
    APPEND IT_SQL.
    CLEAR IT_SQL.
  ENDIF.

  FIND 'TYPE' IN STR.
  IF SY-SUBRC = 0 AND L_BEGIN_SQL = 'X'.
    DATA(L_BEGIN_STRUC) = 'X'."sql 开始标识
  ELSE.
    L_BEGIN_STRUC = ''.
  ENDIF.

  IF L_BEGIN_STRUC = 'X'.
    SPLIT STR AT 'TYPE' INTO DATA(STR1) DATA(STR2).
    CONDENSE STR1 NO-GAPS.
    IT_STRUC-FIELDNAME = STR1.
    SPLIT STR2 AT '-' INTO DATA(STR3) DATA(STR4).
    CONDENSE STR3 NO-GAPS.
    IT_STRUC-TABNAME = STR3.
    APPEND IT_STRUC.
  ENDIF.

  FIND '.' IN STR.
  IF SY-SUBRC = 0 AND L_BEGIN_SQL = 'X'.
    EXIT.
  ENDIF.

  CLEAR:STR,STR1,STR2,STR3,STR4.
ENDLOOP.

READ REPORT 'ZGIT025A' INTO IT_REPORT.

"删除指定定义的IT_Data
READ TABLE IT_REPORT WITH KEY ROW = 'DATA:BEGIN OF IT_DATA OCCURS 0,'.
IF SY-SUBRC = 0.
  DATA(L_INDEX) = SY-TABIX.

  DELETE IT_REPORT INDEX L_INDEX.
  DELETE IT_REPORT INDEX L_INDEX.
  DELETE IT_REPORT INDEX L_INDEX.
ELSE.
  RETURN.
ENDIF.


"插入SQL
INSERT LINES OF IT_SQL INTO  IT_REPORT INDEX  L_INDEX.



"创建laygout
DATA:L_LAYOUT TYPE STRING.
LOOP AT IT_STRUC.
  AT FIRST.
    L_LAYOUT = '  '''' ''X'' ''X'' '''' '''.
    IT_LAYOUT-ROW = 'MACRO_FILL_FCAT L_COLPOS ' && ' ''XZ'' ''选择'' '&& L_LAYOUT  && '' && '''' && ' ''' && '''.'.
    APPEND IT_LAYOUT.
    CLEAR:IT_LAYOUT.

    L_LAYOUT = '  '''' '''' '''' '''' '''.
    IT_LAYOUT-ROW = 'MACRO_FILL_FCAT L_COLPOS ' && ' ''RZ'' ''日志'' '&& L_LAYOUT  && '' && '''' && ' ''' && '''.'.
    APPEND IT_LAYOUT.
    CLEAR:IT_LAYOUT.
  ENDAT.

  L_LAYOUT = ''' '''' '''' '''' '''' '''' '''.
  IT_LAYOUT-ROW = 'MACRO_FILL_FCAT L_COLPOS ''' && IT_STRUC-FIELDNAME && L_LAYOUT  && IT_STRUC-TABNAME && ''' ''' && IT_STRUC-FIELDNAME && '''.'.

  APPEND IT_LAYOUT.
  CLEAR:IT_LAYOUT,L_LAYOUT.
ENDLOOP.

"插入LAYOUT
LOOP AT IT_REPORT.
  STR = IT_REPORT-ROW.
  TRANSLATE STR TO UPPER CASE.
  "创建结构
  IF STR IS NOT INITIAL.
    CONDENSE STR NO-GAPS.
    FIND  STR IN  '  DATA:L_COLPOSTYPELVC_S_FCAT-COL_POS.'.
    IF SY-SUBRC = 0.
      L_INDEX = SY-TABIX + 1.
      INSERT LINES OF IT_LAYOUT  INTO IT_REPORT INDEX L_INDEX.
    ENDIF.
  ENDIF.
  CLEAR:STR.
ENDLOOP.

"写入报表
WRITE:'asdfad'.
*INSERT REPORT PROGNAME FROM IT_REPORT.
