*&---------------------------------------------------------------------*
*& Report ZGIT020
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT020.
DATA: GT_FIELDCAT TYPE LVC_T_FCAT WITH HEADER LINE.
DATA: GS_LAYOUT TYPE LVC_S_LAYO.
DATA: GRID_R       TYPE  REF  TO  CL_GUI_ALV_GRID,
      GRID_R2      TYPE  REF  TO  CL_GUI_ALV_GRID,
      CONTAINER_R  TYPE  REF  TO  CL_GUI_DOCKING_CONTAINER,
      REF_SPLITTER TYPE REF TO  CL_GUI_SPLITTER_CONTAINER,
      REF_CELL     TYPE REF TO  CL_GUI_CONTAINER.
DATA:BEGIN OF GT_DATA OCCURS 0,
       VAL1(40),
       VAL2(40),
     END OF GT_DATA.
CLASS LCL_EVENT_RECEIVER DEFINITION.
  PUBLIC SECTION.
    METHODS:
      HANDLE_PRINT_TOP_OF_PAGE FOR EVENT PRINT_TOP_OF_PAGE OF
        CL_GUI_ALV_GRID,
      HANDLE_TOP_OF_PAGE FOR EVENT TOP_OF_PAGE OF
        CL_GUI_ALV_GRID.
ENDCLASS. "o_lcl_event_receiver DEFINITION

DATA: O_EVENT_RECEIVER TYPE REF TO LCL_EVENT_RECEIVER,
      O_HTML           TYPE REF TO CL_DD_DOCUMENT.
CLASS LCL_EVENT_RECEIVER IMPLEMENTATION.
  METHOD HANDLE_PRINT_TOP_OF_PAGE.
  ENDMETHOD. "handle_print_top_of_page
  METHOD HANDLE_TOP_OF_PAGE.
  ENDMETHOD. "handle_top_of_page
ENDCLASS.

START-OF-SELECTION.

  PERFORM INITAL.

  DEFINE FILL_FDCAT.
    CLEAR GT_FIELDCAT.
    GT_FIELDCAT-FIELDNAME = &1.
    GT_FIELDCAT-SCRTEXT_L = &2.
    APPEND GT_FIELDCAT.
  END-OF-DEFINITION.

  FILL_FDCAT 'VAL1' '列1'.
  FILL_FDCAT 'VAL2' '列2'.
  CALL SCREEN 100.

FORM INITAL .
  GT_DATA-VAL1 = 'CELL1'.
  GT_DATA-VAL2 = 'CELL2'.
  APPEND GT_DATA.
ENDFORM.


MODULE INIT_0100 OUTPUT.
  CREATE OBJECT CONTAINER_R
    EXPORTING
      REPID     = SY-REPID
      DYNNR     = SY-DYNNR
      EXTENSION = 2000.

  CREATE OBJECT REF_SPLITTER
    EXPORTING
      PARENT  = CONTAINER_R
      ROWS    = 1 "将父容器分成两个子容器
      COLUMNS = 2.

  "得到第一行第一列子容器
  CALL METHOD REF_SPLITTER->GET_CONTAINER
    EXPORTING
      ROW       = 1
      COLUMN    = 1
    RECEIVING
      CONTAINER = REF_CELL.

  CREATE OBJECT GRID_R "创建第一个ALV，并放在左边子容器中
    EXPORTING
      I_PARENT = REF_CELL.

  CREATE OBJECT O_HTML
    EXPORTING
      STYLE            = 'ALV_GRID'
      BACKGROUND_COLOR = 35.

  CALL METHOD GRID_R->LIST_PROCESSING_EVENTS
    EXPORTING
      I_EVENT_NAME = 'TOP_OF_PAGE'
      I_DYNDOC_ID  = O_HTML.

  CALL METHOD O_HTML->ADD_TEXT
    EXPORTING
      TEXT         = TEXT-049
      SAP_EMPHASIS = TEXT-051.

  CALL METHOD O_HTML->DISPLAY_DOCUMENT
    EXPORTING
      PARENT = REF_CELL.

  CALL METHOD GRID_R->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
      IS_LAYOUT       = GS_LAYOUT
    CHANGING
      IT_OUTTAB       = GT_DATA[]
      IT_FIELDCATALOG = GT_FIELDCAT[].

  "得到第一行第二列容器
  CALL METHOD REF_SPLITTER->GET_CONTAINER
    EXPORTING
      ROW       = 1
      COLUMN    = 2
    RECEIVING
      CONTAINER = REF_CELL.

  CREATE OBJECT GRID_R2 "创建第一个ALV，并放在右边子容器中
    EXPORTING
      I_PARENT = REF_CELL.

  CALL METHOD GRID_R2->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
      IS_LAYOUT       = GS_LAYOUT
    CHANGING
      IT_OUTTAB       = GT_DATA[]
      IT_FIELDCATALOG = GT_FIELDCAT[].

ENDMODULE.

MODULE STATUS_0100 OUTPUT.
  SET PF-STATUS 'PF-STATUS'.
ENDMODULE.

MODULE USER_EXIT_0100 INPUT.
  LEAVE TO SCREEN 0.
ENDMODULE.
