*&---------------------------------------------------------------------*
*& Report ZGIT26
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT026.
DATA:WA_ORDER_HEADER_IN     TYPE BAPISDHD1,
     WA_ORDER_HEADER_INX    TYPE BAPISDHD1X,
     IT_RETURN_SO2          TYPE STANDARD TABLE OF BAPIRET2 WITH HEADER LINE,
     IT_ORDER_ITEMS_IN      TYPE STANDARD TABLE OF BAPISDITM  WITH HEADER LINE,
     IT_ORDER_ITEMS_INX     TYPE STANDARD TABLE OF BAPISDITMX  WITH HEADER LINE,
     IT_ORDER_PARTNERS      TYPE STANDARD TABLE OF BAPIPARNR  WITH HEADER LINE,
     IT_ORDER_SCHEDULES_IN  TYPE STANDARD TABLE OF BAPISCHDL  WITH HEADER LINE,
     IT_ORDER_SCHEDULES_INX TYPE STANDARD TABLE OF BAPISCHDLX  WITH HEADER LINE,
     IT_CFG_CFG             TYPE STANDARD TABLE OF BAPICUCFG  WITH HEADER LINE,
     IT_CFG_INST            TYPE STANDARD TABLE OF BAPICUINS  WITH HEADER LINE,
     IT_CFG_VAL             TYPE STANDARD TABLE OF BAPICUVAL  WITH HEADER LINE,
     IT_CFG_REFINST         TYPE STANDARD TABLE OF BAPICUREF  WITH HEADER LINE.
DATA:L_SALES TYPE VBAK-VBELN.


SELECT SINGLE CUOBJ
     INTO @DATA(G_CUOBJ)
     FROM VBAP
     WHERE VBELN = '500002967'.

DATA:IT_CONFIG_OLD TYPE IBCO2_INSTANCE_TAB2.
CALL FUNCTION 'CUCB_GET_CONFIGURATION'
  EXPORTING
    INSTANCE                     = G_CUOBJ
  IMPORTING
    CONFIGURATION                = IT_CONFIG_OLD
  EXCEPTIONS
    INVALID_INPUT                = 1
    INVALID_INSTANCE             = 2
    INSTANCE_IS_A_CLASSIFICATION = 3
    OTHERS                       = 4.


WA_ORDER_HEADER_IN-DOC_TYPE  = 'ZINS'. "销售订单类型 正式订单内销
*  WA_SO_HEAD-SALES_ORG = ''."销售组织
*  WA_SO_HEAD-DISTR_CHAN = ''."分销渠道
*  WA_SO_HEAD-DIVISION = ''."产品组
*  WA_SO_HEAD-SALES_GRP = ''."销售组
*  WA_SO_HEAD-REQ_DATE_H = ''."要求的交货日期
*  WA_SO_HEAD-PMNTTRMS = ''."付款条件
*  WA_SO_HEAD-PYMT_METH = ''."付款方式
*  WA_SO_HEAD-ORD_REASON = '100'."订货原因
*  WA_SO_HEADX-ORD_REASON = 'X'."订货原因
WA_ORDER_HEADER_INX-DOC_TYPE = 'X'.

IT_ORDER_ITEMS_IN-ITM_NUMBER = '000010'."销售项目号
IT_ORDER_ITEMS_IN-MATERIAL = '000000101010002879'."
*IT_ORDER_ITEMS_IN-BATCH = '1709250023'."批次
IT_ORDER_ITEMS_IN-PO_ITM_NO = '000001'."-----------------------------写入特性值要加入该字段对应配置信息POSEX 字段
IT_ORDER_ITEMS_IN-SALES_UNIT = 'ST'. "销售单位
*  T_SALES_ITEM- = ''."
APPEND  IT_ORDER_ITEMS_IN.

IT_ORDER_ITEMS_INX-ITM_NUMBER = '000010'."销售项目号
IT_ORDER_ITEMS_INX-UPDATEFLAG = 'X'."销售项目号
IT_ORDER_ITEMS_INX-MATERIAL = 'X'."
IT_ORDER_ITEMS_INX-PO_ITM_NO = 'X'.
*IT_ORDER_ITEMS_INX-BATCH = 'X'."批次
IT_ORDER_ITEMS_INX-SALES_UNIT = 'X'."销售单位
APPEND  IT_ORDER_ITEMS_INX.

"销售伙伴
IT_ORDER_PARTNERS-PARTN_ROLE = 'WE'."送达方
IT_ORDER_PARTNERS-PARTN_NUMB = '0000060014'."
*  IT_ORDER_PARTNERS-ITM_NUMBER = '000010'."
APPEND IT_ORDER_PARTNERS.

IT_ORDER_PARTNERS-PARTN_ROLE = 'SP'."售达方
IT_ORDER_PARTNERS-PARTN_NUMB = '0000060014'."
*  IT_ORDER_PARTNERS-ITM_NUMBER = '000010'."
APPEND IT_ORDER_PARTNERS.

"交货计划行
IT_ORDER_SCHEDULES_IN-ITM_NUMBER = '000010'."销售订单行
IT_ORDER_SCHEDULES_IN-SCHED_LINE = '0001'."销售订单行
IT_ORDER_SCHEDULES_IN-REQ_DATE = SY-DATUM."计划行日期
*  IT_ORDER_SCHEDULES_IN-DATE_TYPE = '1'."日期类型 1 = D
IT_ORDER_SCHEDULES_IN-REQ_QTY = '10'."以销售单位计的订单数量
APPEND IT_ORDER_SCHEDULES_IN.

IT_ORDER_SCHEDULES_INX-ITM_NUMBER = '000010'."销售订单行
IT_ORDER_SCHEDULES_INX-SCHED_LINE = '0001'."销售订单行
IT_ORDER_SCHEDULES_INX-UPDATEFLAG = 'X'."更新标识
IT_ORDER_SCHEDULES_INX-REQ_DATE = 'X'."计划行日期
*  IT_ORDER_SCHEDULES_INX-DATE_TYPE = 'X'."日期类型
IT_ORDER_SCHEDULES_INX-REQ_QTY = 'X'."以销售单位计的订单数量
APPEND IT_ORDER_SCHEDULES_INX.

*  IT_SALES_CONDITIONS-ITM_NUMBER = '000010'."条件项目号
*  IT_SALES_CONDITIONS-COND_TYPE = 'PR11'."条件类型
*  IT_SALES_CONDITIONS-COND_VALUE = '10'."条件金额
*  APPEND IT_SALES_CONDITIONS.
*
*  IT_SALES_CONDITIONSX-ITM_NUMBER = '000010'.
*  IT_SALES_CONDITIONSX-COND_TYPE = 'X'."条件类型
*  IT_SALES_CONDITIONSX-COND_VALUE = 'X'."条件金额
*  APPEND IT_SALES_CONDITIONSX.


IT_CFG_REFINST-POSEX = '000001'.
IT_CFG_REFINST-CONFIG_ID = '000001'.
IT_CFG_REFINST-INST_ID = '00000001'.
APPEND  IT_CFG_REFINST.
CLEAR  IT_CFG_REFINST.

IT_CFG_CFG-POSEX =  '000001'.
IT_CFG_CFG-CONFIG_ID = '000001'.
IT_CFG_CFG-ROOT_ID = '00000001'.
IT_CFG_CFG-COMPLETE = 'T'.
IT_CFG_CFG-CONSISTENT = 'T'.
APPEND IT_CFG_CFG.
CLEAR IT_CFG_CFG.

IT_CFG_INST-CONFIG_ID     =  '000001'.       "External configuration ID (temporary)
IT_CFG_INST-INST_ID       =  '00000001'.     "Instance number in the configuration
IT_CFG_INST-OBJ_TYPE      =  'MARA'.         "Object type
IT_CFG_INST-CLASS_TYPE    =  '300'.          "Class type
IT_CFG_INST-OBJ_KEY       =  '000000101010002879'.""WA_ITEM-MATNR.  " Object key
IT_CFG_INST-OBJECT_GUID =  '000000101010002879'.
IT_CFG_INST-PERSIST_ID_TYPE = 'G'.
IT_CFG_INST-QUANTITY      = '10'."WA_ITEM-KWMENG.  "Instance Quantity
IT_CFG_INST-QUANTITY_UNIT = 'ST'.
IT_CFG_INST-COMPLETE = 'T'.
IT_CFG_INST-CONSISTENT = 'T'.
APPEND IT_CFG_INST.
CLEAR IT_CFG_INST.

*********ORDER_CFGS_VALUE  of type BAPICUVAL with work area wa_cfg_val
*** for CHARCTERISTIC1
IT_CFG_VAL-CONFIG_ID = '000001'.               "External configuration ID (temporary)
IT_CFG_VAL-INST_ID = '00000001'.               "Instance number in the configuration
IT_CFG_VAL-CHARC = 'ZC_501500001102_TX'.       "Characteristic Name
IT_CFG_VAL-VALUE = '501500001103_PT'.          "Characteristic Value
IT_CFG_VAL-VALCODE = '1'.
IT_CFG_VAL-VALUE_LONG = '501500001103_PT'.                    "Value Type: Interval Limits - Single Values

APPEND IT_CFG_VAL.
CLEAR IT_CFG_VAL.



CALL FUNCTION 'BAPI_SALESORDER_CREATEFROMDAT2'
  EXPORTING
    ORDER_HEADER_IN     = WA_ORDER_HEADER_IN
    ORDER_HEADER_INX    = WA_ORDER_HEADER_INX
  IMPORTING
    SALESDOCUMENT       = L_SALES
  TABLES
    RETURN              = IT_RETURN_SO2
    ORDER_ITEMS_IN      = IT_ORDER_ITEMS_IN
    ORDER_ITEMS_INX     = IT_ORDER_ITEMS_INX
    ORDER_PARTNERS      = IT_ORDER_PARTNERS
    ORDER_SCHEDULES_IN  = IT_ORDER_SCHEDULES_IN
    ORDER_SCHEDULES_INX = IT_ORDER_SCHEDULES_INX
    ORDER_CFGS_REF      = IT_CFG_CFG
    ORDER_CFGS_INST     = IT_CFG_INST
    ORDER_CFGS_VALUE    = IT_CFG_VAL
    ORDER_CFGS_REFINST  = IT_CFG_REFINST.
LOOP AT IT_RETURN_SO2 ASSIGNING FIELD-SYMBOL(<WA_RETURN_SO2>) WHERE TYPE = 'E' OR TYPE = 'A'.
ENDLOOP.
IF SY-SUBRC = 0.
  CALL FUNCTION 'BAPI_TRANSACTION_ROLLBACK'.
ELSE.
  CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
    EXPORTING
      WAIT = 'X'.
  WRITE:L_SALES.
ENDIF.

SELECT SINGLE CUOBJ
     INTO @G_CUOBJ
     FROM VBAP
     WHERE VBELN = @L_SALES.
DATA:OO_CBASE TYPE REF TO CL_CUX_CBASE_CORE,
     GT_VALUE TYPE CUXT_CUVAL_T,
     GT_CUVAL TYPE CUXT_CUVAL_T,
     G_ATINN  TYPE CABN-ATINN,
     WA_MSG   TYPE BAPIRET2.
CREATE OBJECT OO_CBASE.
TRY.
    CALL METHOD OO_CBASE->GET_CBASE
      EXPORTING
        IV_ROOT_CUOBJ   = G_CUOBJ
        IV_LANGUAGE     = SY-LANGU
      IMPORTING
*       ev_root_persist_id      =
*       es_cfg_head     =
*       et_instances    =
*       et_part_of      =
        ET_VALUES       = GT_VALUE
*       et_var_keys     =
        ET_RESTRICTIONS = GT_CUVAL
*       et_blob         =
      .
  CATCH CX_CBASE_ERROR .
ENDTRY.

CALL FUNCTION 'CUCB_GET_CONFIGURATION'
  EXPORTING
    INSTANCE                     = G_CUOBJ
  IMPORTING
    CONFIGURATION                = IT_CONFIG_OLD
  EXCEPTIONS
    INVALID_INPUT                = 1
    INVALID_INSTANCE             = 2
    INSTANCE_IS_A_CLASSIFICATION = 3
    OTHERS                       = 4.

CALL FUNCTION 'CUCB_SET_CONFIGURATION'
  EXPORTING
    ROOT_INSTANCE                = G_CUOBJ
  CHANGING
    CONFIGURATION                = IT_CONFIG_OLD
  EXCEPTIONS
    INVALID_INPUT                = 1
    INVALID_INSTANCE             = 2
    INSTANCE_IS_A_CLASSIFICATION = 3
    OTHERS                       = 4.
COMMIT WORK.




*CALL FUNCTION 'CUCB_CONFIGURATION_TO_DB'
*  EXPORTING
*    ROOT_INSTANCE                 = G_CUOBJ
*    ROOT_OBJECT                   = G_OBJECT
**   FORCE_NEW_INSTANCE            =
**   IV_WITHOUT_COMMIT_UPDATE      = ' '
**   IV_MATERIAL                   =
**   IV_LOCATION                   =
**   IV_TECHS                      =
**   IMPORTING
**   NEW_INSTANCE                  =
**   TABLES
**   EXP_NEW_NESTED_CUOBJS         =
*  EXCEPTIONS
*    INVALID_INSTANCE              = 1
*    INVALID_ROOT_INSTANCE         = 2
*    NO_CHANGES                    = 3
*    ALREADY_REGISTERED_FOR_UPDATE = 4
*    INSTANCE_IS_A_CLASSIFICATION  = 5
*    OTHERS                        = 6.
