*&---------------------------------------------------------------------*
*& Report ZGIT027
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT027.

DATA: V_FNAME TYPE STRING VALUE 'ZTEST_GIT'.
DATA: IT_PARM TYPE ABAP_FUNC_PARMBIND_TAB,
      IT_EXCP TYPE ABAP_FUNC_EXCPBIND_TAB,
      WA_PARM TYPE ABAP_FUNC_PARMBIND,
      WA_EXCP TYPE ABAP_FUNC_EXCPBIND.


"标参数传递
SELECT * UP TO 1 ROWS INTO TABLE @DATA(IT_MARA) FROM MARA.
WA_PARM-NAME = 'IT_MARA'.
WA_PARM-KIND = ABAP_FUNC_TABLES.
GET REFERENCE OF IT_MARA INTO WA_PARM-VALUE.
INSERT WA_PARM INTO TABLE IT_PARM.
CLEAR:WA_PARM.

"导入参数传递
DATA:L_MATNR TYPE MATNR VALUE 'R-1001'.
WA_PARM-NAME = 'MATNR'.
WA_PARM-KIND = ABAP_FUNC_EXPORTING.
GET REFERENCE OF L_MATNR INTO WA_PARM-VALUE."要和函数的类型一样不然会报类型冲突
INSERT WA_PARM INTO TABLE IT_PARM.
CLEAR:WA_PARM.

"导出参数传递
DATA:L_MAKTX TYPE MAKTX .
WA_PARM-NAME = 'MAKTX'.
WA_PARM-KIND = ABAP_FUNC_IMPORTING.
GET REFERENCE OF L_MAKTX INTO WA_PARM-VALUE."要和函数的类型一样不然会报类型冲突
INSERT WA_PARM INTO TABLE IT_PARM.
CLEAR:WA_PARM.

WA_EXCP-NAME = 'CX_SY_DYN_CALL_ILLEGAL_TYPE'.
WA_EXCP-VALUE = '1'.
INSERT WA_EXCP INTO TABLE IT_EXCP.

"动态函数调用
CALL FUNCTION V_FNAME
  PARAMETER-TABLE
  IT_PARM
  EXCEPTION-TABLE
  IT_EXCP.

LOOP AT IT_MARA ASSIGNING FIELD-SYMBOL(<WA_MARA>).

ENDLOOP.
