*&---------------------------------------------------------------------*
*& Report ZGIT021
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZGIT021.



DATA: JOB_OUTPUT_INFO      TYPE SSFCRESCL,
      DOCUMENT_OUTPUT_INFO TYPE SSFCRESPD,
      JOB_OUTPUT_OPTIONS   TYPE SSFCRESOP,
      OUTPUT_OPTIONS       TYPE SSFCOMPOP,
      CONTROL_PARAMETERS   TYPE SSFCTRLOP,
      L_FORMNAME           TYPE TDSFNAME VALUE 'ZPPSF059_2'.

*& OTF 转换
DATA: LT_OTF   TYPE STANDARD TABLE OF ITCOO,
      LT_DOCS  TYPE STANDARD TABLE OF DOCS,
      LT_LINES TYPE STANDARD TABLE OF TLINE.

*& 数据
DATA: V_LEN_IN       TYPE SO_OBJ_LEN,
      V_LANGUAGE     TYPE SFLANGU VALUE 'E',
      V_E_DEVTYPE    TYPE RSPOPTYPE,
      V_BIN_FILESIZE TYPE I,
      V_NAME         TYPE STRING,
      V_PATH         TYPE STRING,
      V_FULLPATH     TYPE STRING,
      V_FILTER       TYPE STRING,
      V_UACT         TYPE I,
      V_GUIOBJ       TYPE REF TO CL_GUI_FRONTEND_SERVICES,
      V_FILENAME     TYPE STRING,
      V_FM_NAME      TYPE RS38L_FNAM.

*& Class Declarations
DATA: GO_SEND_REQUEST  TYPE REF TO  CL_BCS,
      GO_DOCUMENT      TYPE REF TO  CL_DOCUMENT_BCS,

      LO_RECIPIENT     TYPE REF TO  IF_RECIPIENT_BCS,
      LO_BCS_EXCEPTION TYPE REF TO  CX_BCS.

DATA: GV_SUBJECT      TYPE SO_OBJ_DES,
      GV_TITLE        TYPE SO_OBJ_DES,
      LV_LEN          TYPE SO_OBJ_LEN,
      LI_CONTENT_HEX  TYPE SOLIX_TAB,
      LW_CONTENT      TYPE SOLI,
      LS_CONTENT_HEX  TYPE SOLIX,
      LI_CONTENT_TXT  TYPE SOLI_TAB,
      LI_OBJHEAD      TYPE SOLI_TAB,
      LV_TRANSFER_BIN TYPE SX_BOOLEAN,
      LV_EMAIL        TYPE AD_SMTPADR,
      LV_SENT_TO_ALL  TYPE OS_BOOLEAN.

DATA: LI_OTF TYPE TABLE OF ITCOO,
      LW_OTF TYPE ITCOO.

DATA: NUMBER(4) TYPE C.

********Variable Declarations ****************************
DATA: GV_FORM_NAME    TYPE RS38L_FNAM, " Used to store the function module generated by Smartform
      GV_BIN_FILESIZE TYPE I, " Store the file size
      GV_POS          TYPE I,
      GV_LEN          TYPE I,
      GV_TAB_LINES    TYPE I.
*******Constants ******************************************
DATA : GC_TEXT(11)    TYPE C VALUE 'Form Output',
       GC_TST(3)      TYPE C VALUE 'TST',
       GC_TESTING(20) TYPE C.
********Work Area Declarations ****************************
DATA: GS_DOCDATA TYPE SODOCCHGI1, " Data of an object which can be changed
      GS_CTRLOP  TYPE SSFCTRLOP, " Smart Forms: Control structure
      GS_OUTOPT  TYPE SSFCOMPOP, " SAP Smart Forms: Smart Composer (transfer) options
      GS_OTFDATA TYPE SSFCRESCL, " Smart Forms: Return value at end of form printing
      GS_RECLIST TYPE SOMLRECI1, " SAPoffice: Structure of the API Recipient List
      GS_PDF_TAB TYPE TLINE, " Workarea for SAP Script Text Lines
      GS_OBJBIN  TYPE SOLISTI1, " SAPoffice: Single List with Column Length 255
      GS_OBJPACK TYPE SOPCKLSTI1. " SAPoffice: Description of Imported Object Components
********Internal tables Declarations ****************************
DATA: GT_RECLIST TYPE TABLE OF SOMLRECI1, " SAPoffice: Structure of the API Recipient List
      GT_PDF_TAB TYPE TABLE OF TLINE, " SAPscript: Text Lines
      I_OBJTXT   TYPE SOLI,
      T_OBJTXT   TYPE BCSY_TEXT,
      GT_OTF     TYPE TABLE OF ITCOO, " OTF Structure
      GT_OBJBIN  TYPE TABLE OF SOLISTI1, " SAPoffice: Single List with Column Length 255
      GT_OBJPACK TYPE TABLE OF SOPCKLSTI1. " SAPoffice: Description of Imported Object Components
DATA: CUSTOMER    TYPE SCUSTOM,
      BOOKINGS    TYPE TY_BOOKINGS,
      CONNECTIONS TYPE TY_CONNECTIONS.
CLEAR : GV_FORM_NAME,
GS_CTRLOP,
GS_OUTOPT,
GS_OTFDATA,
GV_BIN_FILESIZE,
GV_POS,
GV_LEN,
GV_TAB_LINES.

DATA:GS_HEAD1 LIKE ZPPSF059_HEAD1, "定义的表头结构  把需要的字段放进去
     GT_HEAD1 LIKE STANDARD TABLE OF ZPPSF059_HEAD1. " 内表
DATA:GS_ITEM1 LIKE ZPPSF059_ITEM1,
     GT_ITEM1 LIKE STANDARD TABLE OF ZPPSF059_ITEM1.
DATA:GS_ITEM2 LIKE ZPPSF059_ITEM2,
     GT_ITEM2 LIKE STANDARD TABLE OF ZPPSF059_ITEM2.
DATA:GS_ITEM3 LIKE ZPPSF059_ITEM3,
     GT_ITEM3 LIKE STANDARD TABLE OF ZPPSF059_ITEM3.


CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
  EXPORTING
    FORMNAME           = 'ZTEST'
  IMPORTING
    FM_NAME            = V_FM_NAME
  EXCEPTIONS
    NO_FORM            = 1
    NO_FUNCTION_MODULE = 2
    OTHERS             = 3.
IF SY-SUBRC <> 0.
  MESSAGE '无法找到FUNCTION NAME' TYPE 'S' DISPLAY LIKE 'E'.
  EXIT.
ENDIF.

OUTPUT_OPTIONS-TDDEST        = 'LP01'.

CONTROL_PARAMETERS-NO_DIALOG = 'X'.
CONTROL_PARAMETERS-GETOTF    = 'X'.



*--------------------------打印函数---------------------------------*
CALL FUNCTION V_FM_NAME
  EXPORTING
    CONTROL_PARAMETERS   = CONTROL_PARAMETERS
    OUTPUT_OPTIONS       = OUTPUT_OPTIONS
  IMPORTING
    DOCUMENT_OUTPUT_INFO = DOCUMENT_OUTPUT_INFO
    JOB_OUTPUT_INFO      = JOB_OUTPUT_INFO
    JOB_OUTPUT_OPTIONS   = JOB_OUTPUT_OPTIONS
  EXCEPTIONS
    FORMATTING_ERROR     = 1
    INTERNAL_ERROR       = 2
    SEND_ERROR           = 3
    USER_ANCELED         = 4.


IF JOB_OUTPUT_INFO-OTFDATA[] IS INITIAL.
  MESSAGE S398(00) WITH '工程变更号' &&  ' PDF文件内容生成错误' DISPLAY LIKE 'E'.
ENDIF.

LI_OTF[] = JOB_OUTPUT_INFO-OTFDATA.

CALL FUNCTION 'CONVERT_OTF_2_PDF'
  IMPORTING
    BIN_FILESIZE           = V_BIN_FILESIZE
  TABLES
    OTF                    = JOB_OUTPUT_INFO-OTFDATA
    DOCTAB_ARCHIVE         = LT_DOCS
    LINES                  = LT_LINES
  EXCEPTIONS
    ERR_CONV_NOT_POSSIBLE  = 1
    ERR_OTF_MC_NOENDMARKER = 2
    OTHERS                 = 3.

*CLEAR GS_DOCDATA.
*GS_DOCDATA-OBJ_NAME = GC_TST.
*CONCATENATE '工程变更:' ECN_DATA-AENNR  INTO GC_TESTING.
*GS_DOCDATA-OBJ_DESCR = GC_TESTING.
*GV_TITLE = '邮件主题'.

CLEAR: GS_OBJPACK.    REFRESH: GT_OBJPACK.
"&*** ADD TXT ***
REFRESH  T_OBJTXT.
I_OBJTXT = 'Dear All :'.
APPEND I_OBJTXT TO T_OBJTXT.
I_OBJTXT = '       您好!有新的工程变更，请查阅附件！'.
APPEND I_OBJTXT TO T_OBJTXT.
I_OBJTXT = '       此邮件为ERP系统ECN变更时自动转发，请勿直接回复！有疑问时请联系工程相关人员！谢谢！'.
APPEND I_OBJTXT TO T_OBJTXT.


"& Create persistent send request
GO_SEND_REQUEST = CL_BCS=>CREATE_PERSISTENT( ).

GO_DOCUMENT = CL_DOCUMENT_BCS=>CREATE_DOCUMENT(
  I_TYPE      = 'RAW'    "邮件格式
  I_TEXT      = T_OBJTXT "邮件类型
  I_SUBJECT   = '邮件主题' ).


REFRESH LI_CONTENT_TXT.
"填充附件数据
LOOP AT LI_OTF INTO LW_OTF.
  CLEAR LW_CONTENT.
  CONCATENATE LW_OTF-TDPRINTCOM LW_OTF-TDPRINTPAR INTO LW_CONTENT.

  APPEND LW_CONTENT TO LI_CONTENT_TXT.
ENDLOOP.


"& FM to convert OTF to PDF
CALL FUNCTION 'SX_OBJECT_CONVERT_OTF_PDF'
  EXPORTING
    FORMAT_SRC      = 'OTF'
    FORMAT_DST      = 'PDF'
  CHANGING
    TRANSFER_BIN    = LV_TRANSFER_BIN
    CONTENT_TXT     = LI_CONTENT_TXT
    CONTENT_BIN     = LI_CONTENT_HEX
    OBJHEAD         = LI_OBJHEAD
    LEN             = LV_LEN
  EXCEPTIONS
    ERR_CONV_FAILED = 1
    OTHERS          = 2.

GO_DOCUMENT->ADD_ATTACHMENT(
  I_ATTACHMENT_TYPE     = 'PDF'
  I_ATTACHMENT_SUBJECT  = '附件名称'
  I_ATTACHMENT_SIZE     = LV_LEN
  I_ATT_CONTENT_HEX     = LI_CONTENT_HEX ).


"& Add document object to send request
CALL METHOD GO_SEND_REQUEST->SET_DOCUMENT( GO_DOCUMENT ).

"& Add recipient (e-mail address)
"& create recipient object


LO_RECIPIENT = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS( 'HEM@KUSAUTO.COM.CN' ).

"& Assign recipient to email
CALL METHOD GO_SEND_REQUEST->ADD_RECIPIENT
  EXPORTING
    I_RECIPIENT = LO_RECIPIENT.
"    i_express   = 'X'.  "紧急邮件



"& Send email
CALL METHOD GO_SEND_REQUEST->SEND( I_WITH_ERROR_SCREEN = 'X' ).

*        "& Add recipient object to send request
*        go_send_request->add_recipient( lo_recipient ).

COMMIT WORK.
MESSAGE '邮件发送成功！' TYPE 'S' DISPLAY LIKE 'S'.
